config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :clinics
  get 'camps/reports/' => 'camps#reports'
  get 'camps/reports/:id' => 'camps#reports'
  resources :camps
  resources :charges
  resources :students
  get '/campers/success/:id' => 'campers#success', :as => 'success'
  resources :campers
  get '/about' => 'home#about'
  get '/about/jordan' => 'home#jordan'
  get '/about/staff' => 'home#staff'
  get '/privacypolicy' => 'home#privacy_policy'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  get '/admin/clinics' => 'clinics#adminview'
  resources :testimonials
  root to: 'home#welcome'
end

app/models/camp.rb
class Camp < ActiveRecord::Base
  validates :name, :price, :starting_date, :ending_date, :description, :location_name, :location_street_one, :city, :state, :zipcode, presence: true
  validates :price, numericality: true

  # has_and_belongs_to_many :users
  has_many :campers

  scope :expired, -> { where('date_time < ?', Date.yesterday) }


  def expired?
    if self.starting_date <= Date.today
      return true
    else
      return false
    end
  end

  def self.upcoming
    Camp.all.where('starting_date >= ?', Chronic.parse('yesterday'))
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |camper|
        csv << camper.attributes.values_at(*column_names)
      end
    end
  end

  def report_name
    "#{name}: #{starting_date}"
  end

  def google_map_name
    "#{self.location_street_one.split(' ').join('+')}+#{self.city.split(' ').join('+')}+#{self.state.split(' ').join('+')}"
  end

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  helper_method :sort_column, :sort_direction

  def index
    @camps = Camp.where("starting_date >= ?", Chronic.parse('yesterday')).order(starting_date: :asc)
  end

  def adminview
    @camps = Camp.order(starting_date: :desc)
  end

  def show
    @camp = Camp.find(params[:id])
    @camper = Camper.new
  end

  def reports
    @camp = Camp.find(camp_id)
    @campers = @camp.campers.order(sort_column + " " + sort_direction)
    @camps = Camp.all.order(starting_date: :asc)
    respond_to do |format|
      format.html
      format.csv {send_data @campers.to_csv, filename: "#{@camp.name}_as_of_#{DateTime.now.strftime "%Y-%m-%d_%H:%M:%S"}.csv"}
      #format.xls {send_data @campers.to_csv(col_sep: "\t"), filename: "#{@camp.name}_as_of_#{DateTime.now.strftime "%Y-%m-%d_%H:%M:%S"}.xls"}
    end
  end

  def new
    @camp = Camp.new
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.valid?
      # @camp.starting_date = Chronic.parse(params[:camp][:starting_date])
      # @camp.ending_date = Chronic.parse(params[:camp][:ending_date])
      @camp.name = params[:camp][:name]
      @camp.location_name = capitalize_each_word(params[:camp][:location_name])
      @camp.city = capitalize_each_word(params[:camp][:city])
      @camp.save!
      segment_id = MailingList.new_camp_segment(@camp)
      @camp.list_id = segment_id
      @camp.save!
      flash[:alert] = "#{@camp.name} has been created successfully."
      redirect_to @camp
    else
      render :new
    end
  end

  def edit
    @camp = Camp.find(params[:id])
  end

  def update
    @camp = Camp.find(params[:id])
    @camp.update(camp_params)
    if @camp.valid?
      @camp.save!
      flash[:alert] = "#{@camp.name} has been updated successfully."
      redirect_to camps_path
    else
      render :new
    end
  end

  def destroy
    @camp = Camp.find(params[:id])
    flash[:alert] = "#{@camp.name} has been successfully deleted."
    @camp.destroy!
    redirect_to camps_path
  end

  private
  def camp_params
    params.require(:camp).permit(:name, :price, :description, :starting_date, :ending_date, :location_name, :location_street_one, :location_street_two, :city, :state, :zipcode)
  end

  def capitalize_each_word(form_string)
    result_array = []
    form_string.split(' ').each do |word|
      result_array.push(word.capitalize)
    end
    return result_array.join(' ')
  end

  def camp_id
    params[:id] ||= Camp.last.id
  end

  def sort_column
    params[:sort] ||= "age"
    %w[age position experience].include?(params[:sort]) ? params[:sort] : "age"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  # Method to increase remaining slots when total slots is updated

end

app/views/camps/_camps.html.erb
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_zPWECKnej44Flev2zwZDcznJ');
  // ...
</script>

<div class="container">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 clinic-wrap">
  <% if @camps == [] %>
    <div class="col-xs-12 col-sm-10 col-sm-offset-3 bottom-margin">
      <p class="red-text">There are currently no scheduled camps.</p>
    </div>
  <% else %>
    <% @camps.each do |camp| %>
      <div class="col-xs-12 bottom-margin">
        <p><span class="bold"><%= link_to camp.name, camp_path(camp) %></span> - <%= number_to_currency(camp.price) %></p>
        <p><span class="bold">Location</span>: <%= camp.location_name %></p>
        <p><span class="bold">Dates</span>: <%= camp.starting_date.strftime "%A %B %e" %> - <%= camp.ending_date.strftime "%A %B %e" %></p>
        <p><span class="bold">Description</span>: <%= truncate(camp.description, length: 200) %></p>
        <p><%= camp.location_street_one %>, <%= camp.city %>, <%= camp.state %></p>
        <% if current_user != nil && current_user.admin %>
          <p><span class="bold">Spots Taken</span>: <%= camp.campers.length %></p>
        <% end %>
        <% if current_user != nil && current_user.admin %>
          <% if camp.starting_date > DateTime.now %>
            <%= button_to 'edit', edit_camp_path(camp), :method => 'get', class: 'btn btn-info float-left' %>
            <%= button_to "delete", camp, :method => 'delete', class: 'btn btn-danger float-left' %>
          <% end %>
        <% else %>
          <%= link_to 'register', new_camper_path(:camp_id => camp.id), class: 'btn btn-success' %>
          <%= link_to 'more info', camp_path(camp.id), class: 'btn btn-primary' %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/camps/_form.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 red-text">
    <% if @camp.errors.any? %>
      <p>Please correct the following errors:</p>
      <ul>
      <% @camp.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
      </ul>
    <% end %>
  </div>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <%= form_for @camp do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :starting_date %>
        <%= f.text_field :starting_date, class: 'form-control', id: 'starting-date' %>
      </div>

      <div class="form-group">
        <%= f.label :ending_date %>
        <%= f.text_field :ending_date, class: 'form-control', id: 'ending-date' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :location_name %>
        <%= f.text_field :location_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :location_street_one %>
        <%= f.text_field :location_street_one, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :location_street_two %>
        <%= f.text_field :location_street_two, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :state %>
        <%#= select_tag :state, options_for_select(us_states), class: 'form-control' %>
        <%= f.select(:state, options_for_select(us_states)) %>
      </div>

      <div class="form-group">
        <%= f.label :zipcode %>
        <%= f.number_field :zipcode, class: 'form-control' %>
      </div>

        <%= f.submit :class => 'btn btn-default' %>
      <% end %>
  </div>
</div>

app/views/camps/_report_detail.html.erb
  <div class="container">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>
                <%= sortable "age", @camp.id %>
              </th>
              <th><%= sortable "position", @camp.id %></th>
              <th><%= sortable "experience", @camp.id %></th>
              <th>School Name</th>
              <th>Hometown</th>
              <th>Actions</th>
            </tr>
          </thead>
          <% @campers.order(age: :asc).each_with_index do |camper, index| %>
          <tbody>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= camper.first_name %></td>
              <td><%= camper.last_name %></td>
              <td><%= camper.email || 'N/A' %></td>
              <td><%= camper.age %></td>
              <td><%= camper.position %></td>
              <td><%= camper.experience %></td>
              <td><%= camper.school %></td>
              <td><%= camper.city %>, <%= camper.state %></td>
              <td><%= link_to 'Edit', edit_camper_path(camper.id) %> / <%= link_to 'Delete', camper_path(camper.id), :method => "delete" %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/camps/adminview.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/about">About</a></li>
        <li><a href="/camps">Camps</a></li>
        <li><a href="/faq">FAQs</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
      <!-- admin section -->
      <% if current_user != nil && current_user.admin %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/admin/camps">Scheduled Camps</a></li>
            <li><a href="/camps/new">Add a Camp</a></li>
            <li class="divider"></li>
            <li><%= link_to'Log Out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-10 col-xs-offset-1 bottom-margin">
      <h1 class="centered">Admin View of All Camps</h1>
    </div>
  </div>

  <%= render 'camps' %>
</div>

app/views/camps/edit.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>Edit a Camps</h1>
  </div>
</div>

<%= render 'form' %>

app/views/camps/index.html.erb
<%- title "Wolf Lacrosse - Upcoming Camps" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <!-- admin section -->
      <% if current_user != nil && current_user.admin %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><%= link_to'Log Out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1 upcoming-camps">
      <h1 class="centered">Upcoming Camps</h1>
    </div>
  </div>

  <%= render 'camps' %>
</div>

app/views/camps/new.html.erb
<%- title "Wolf Lacrosse - Add a Camp" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h1>Create a New Camp</h1>
    </div>
  </div>

  <%= render 'form' %>
</div>

app/views/camps/reports.html.erb
<%- title "Wolf Lacrosse - Camp Reports" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <!-- admin section -->
      <% if current_user != nil && current_user.admin %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><%= link_to'Log Out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-10 col-xs-offset-1 bottom-margin">
      <h1 class="centered">View Camp Reports</h1>
    </div>
  </div>

  <div class="container">
    <div class="col-xs-12">
      <% if flash[:notice] %>
        <p class="alert"><%= flash[:notice] %></p>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="col-xs-8">
      <%= form_tag '/camps/reports', method: 'get', class: 'form-inline', id: 'report-camp-select' do %>
        <div class="form-group">
          <%= label_tag :id, "Filter by Camp: " %>
          <%= select_tag :id, options_from_collection_for_select(@camps, "id", "report_name", @camp.id), {class: 'form-control'} %>
        </div>
        <div class="form-group">
          <%= submit_tag "Submit", {class: 'form-control', id: 'camp-select-submit-button'} %>
        </div>
      <% end %>
      <p>
        Download:
        <%= link_to "CSV", camps_reports_path(sort: sort_column, direction: sort_direction, id: @camp.id, format:"csv") %>
        <%#= link_to "Excel", camps_reports_path(format:"xls") %>
      </p>
    </div>
  </div>

  <%= render "report_detail" %>

</div>

app/views/camps/reports.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">First Name</Data></Cell>
        <Cell><Data ss:Type="String">Last Name</Data></Cell>
        <Cell><Data ss:Type="String">Age</Data></Cell>
        <Cell><Data ss:Type="String">DOB</Data></Cell>
      </Row>
    <% @campers.each do |camper| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= camper.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= camper.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= camper.age %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= camper.dob %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/camps/show.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <!-- admin section -->
      <% if current_user != nil && current_user.admin %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><%= link_to'Log Out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <!--<div class="col-xs-10 col-xs-offset-1 alert">
    <%= notice %>
  </div> -->

  <div class="col-xs-10 col-xs-offset-1">
    <h1><%= @camp.name %></h1>
    <h4><%= @camp.starting_date.strftime "%A %b %e, %Y" %> - <%= @camp.ending_date.strftime "%A %b %e, %Y" %></h4>
    <hr>
    <p><span class="bold">Location</span>: <%= @camp.location_name %> <br>
      <% if @camp.location_street_two.nil? %>
        <%= @camp.location_street_one %> <br>
      <% else %>
        <%= @camp.location_street_one %>, <%= @camp.location_street_two %>
      <% end %>
      <br>
      <%= @camp.city %>, <%= @camp.state %> <%= @camp.zipcode %>
    </p>
    <p><span class="bold">Description:</span> <%= @camp.description %></p>
  </div>

  <div class="col-xs-5 col-xs-offset-1 bottom-margin ">
    <% unless @camp.expired? %>
      <%= link_to "Register", new_camper_path(:camp_id => @camp.id), class: 'checkout-button' %>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-10 col-sm-offset-1 centered" id="google-map">
    <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["WOLF_GMAPS_KEY"] %>
      &q=<%= @camp.google_map_name %>&zoom=11"></iframe>
  </div>

  </div>

</div>