config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :clinics
  get 'camps/reports/' => 'camps#reports'
  get 'camps/reports/:id' => 'camps#reports'
  resources :camps
  resources :charges
  resources :students
  get '/campers/success/:id' => 'campers#success', :as => 'success'
  resources :campers
  get '/about' => 'home#about'
  get '/about/jordan' => 'home#jordan'
  get '/about/staff' => 'home#staff'
  get '/privacypolicy' => 'home#privacy_policy'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  get '/admin/clinics' => 'clinics#adminview'
  resources :testimonials
  root to: 'home#welcome'
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  include ActiveModel::Validations
  validates :quote, presence: true
  validates_with TestimonialLimitValidator

  def self.at_capacity?
    self.count >= 10 ? true : false
  end

  def self.empty?
    self.count == 0 ? true : false
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!

  def index
    @testimonials = Testimonial.all
  end

  def show
    @testimonial = Testimonial.find(param[:id])
  end

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
    if @testimonial.valid?
      @testimonial.save!
      redirect_to testimonials_path
    else
      render :new
    end
  end

  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  def update
    @testimonial = Testimonial.find(params[:id])
    @testimonial.update(testimonial_params)
    redirect_to testimonials_path
  end

  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy!
    redirect_to testimonials_path
  end

  private
  def testimonial_params
    params.require(:testimonial).permit(:quote, :author)
  end

end

app/views/testimonials/_form.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 red-text">
    <% if @testimonial.errors.any? %>
      <p>Please correct the following errors:</p>
      <ul>
        <% @testimonial.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <%= form_for @testimonial do |f| %>
    <div class="form-group">
      <%= f.label :quote %>
      <%= f.text_area :quote, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-default' %>
    <% end %>
  </div>

</div>

app/views/testimonials/edit.html.erb
<%- title "Wolf Lacrosse - Edit Testimonial" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h1>Edit Testimonial</h1>
    </div>
  </div>

<%= render 'form' %>

app/views/testimonials/index.html.erb
<%- title "Wolf Lacrosse - All Testimonials" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <!-- admin section -->
      <% if current_user != nil && current_user.admin %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><%= link_to'Log Out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1 upcoming-camps">
      <h1 class="centered">All Testimonials</h1>
    </div>
    <div class="col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1 upcoming-camps">
      <p class="centered">This is the admin-only view of the testimonials. From here you can view, create, edit, and delete any of your existing testimonials.</p>
    </div>
  </div>

  <div class="container testimonial-container all-testimonials">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <% unless @testimonials.at_capacity? %>
        <%= link_to 'New Testimonial', new_testimonial_path, class: 'new-testimonial-btn btn btn-primary' %>
      <% end %>
      <% @testimonials.each do |t| %>
        <div class="testimonial-wrap">
          <p class="quote">
            <i class="fa fa-quote-left"></i>
            <span><%= t.quote %></span>
            <% unless t.author.empty? %>
              <p class="author"><%= t.author %></p>
            <% end %>
          </p>
          <div class="button-wrap">
            <%= button_to 'edit', edit_testimonial_path(t), method: 'get', class: 'btn btn-info float-left' %>
            <%= button_to 'delete', testimonial_path(t), method: 'delete', class: 'btn btn-danger float-left' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/testimonials/new.html.erb
<%- title "Wolf Lacrosse - Add a Testimonial" %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'new_logo_blue.png', class: 'logo-nav' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/camps">Camps</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/about/staff">Staff</a></li>
        <li><a href="/about/jordan">Jordan</a></li>
        <li><a href="<%= new_camper_path %>">Register</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Menu <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/camps/new">Add a Camp</a></li>
            <li><a href="/camps/reports">Camp Reports</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="content-wrap">
  <div class="container">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h1>Add a Testimonial</h1>
    </div>
  </div>

<%= render 'form' %>