config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :clinics
  get 'camps/reports/' => 'camps#reports'
  get 'camps/reports/:id' => 'camps#reports'
  resources :camps
  resources :charges
  resources :students
  get '/campers/success/:id' => 'campers#success', :as => 'success'
  resources :campers
  get '/about' => 'home#about'
  get '/about/jordan' => 'home#jordan'
  get '/about/staff' => 'home#staff'
  get '/privacypolicy' => 'home#privacy_policy'
  # get '/faq' => 'home#faq'
  # get '/contact' => 'home#contact'
  get '/admin/clinics' => 'clinics#adminview'
  resources :testimonials
  root to: 'home#welcome'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <title><%= content_for?(:title) ? content_for(:title) : "Wolf Lacrosse Camps" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "https://js.stripe.com/v2/", 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>

  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-61807503-1', 'auto');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
  </script>
  <!-- End Google Analytics -->
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <%= yield %>

<div class="container-fluid footer">
  <div class="col-sm-3 col-md-2 col-md-offset-2">
    <h4>Company</h4>
    <%= link_to 'Camps', camps_path %> <br>
    <%= link_to 'About', about_path %> <br>
    <%= link_to 'Jordan', about_jordan_path %> <br>
    <%= link_to 'Staff', about_staff_path %> <br>
    <%= link_to 'Register', new_camper_path %> <br>
    <%= link_to 'Privacy Policy', privacypolicy_path %>
  </div>
  <div class="col-sm-3 col-md-2">
    <h4>Camps</h4>
    <%= link_to 'Upcoming Camps', camps_path %> <br>
    <% if current_user == nil %>
      <%= link_to 'Admin Login', new_user_session_path %> <br>
    <% end %>
    <% if current_user != nil && current_user.admin %>
      <%= link_to 'Admin Log Out', destroy_user_session_path, method: 'delete' %> <br>
      <%= link_to 'Add a Camp', new_camp_path %> <br>
      <%= link_to 'Camp Reports', camps_reports_path %> <br>
      <%= link_to 'Testimonials', testimonials_path %>
    <% end %>
  </div>
  <div class="col-sm-3 col-md-2">
    <h4>Contact</h4>
    <a href="mailto:jordan@wolflax.com">Jordan Wolf</a> <br>
    <a href="mailto:george@wolflax.com">George Stein, Camp Director</a> <br>
    <div>(303) 332-8115</div>
  </div>
  <div class="col-sm-3 col-md-2">
    <h4>Sponsors</h4>
    <a href="http://www.cascadehelmets.com/" target="_blank"><%= image_tag 'cascade_logo.png', class: 'sponsor-logo' %></a>
    <a href="http://maveriklacrosse.com/" target="_blank"><%= image_tag 'maverick_logo.png', class: 'sponsor-logo' %></a>
    <a href="http://www.playerxapparel.com/" target="_blank"><%= image_tag 'playerx_logo.png', class: 'sponsor-logo player-x-logo' %></a>
  </div>
  <div class="col-xs-8 col-xs-offset-2">
    <hr>
  </div>
  <div class="col-xs-8 col-xs-offset-2 centered">
    <p class="centered">Follow Us On Social Media</p>
  </div>
  <div class="col-xs-8 col-xs-offset-2 social-media">
    <!-- <i class="fa fa-facebook fa-2x"></i> -->
    <a href="https://twitter.com/TheBigBadWolf31" target="_blank"><i class="fa fa-twitter fa-2x"></i></a>
    <a href="https://www.facebook.com/wolflacrossecamps" target="_blank"><i class="fa fa-facebook fa-2x"></i></a>
    <a href="http://instagram.com/jwolf31" target="_blank"><i class="fa fa-instagram fa-2x"></i></a>
    <!-- <i class="fa fa-youtube-play fa-2x last-icon"></i> -->
  </div>
</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <%= yield %>
</body>
</html>